services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-contabilidad
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pwd
      POSTGRES_DB: contabilidad_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
